image: "python:3.12"

stages:
  - format
  - build

ruff:
  stage: format
  before_script:
      - git config --global user.name "Janitor"
      - git config --global user.email "squad@fz-juelich.de"
      - git remote set-url origin https://squad_janitor:$CI_FORMAT@$CI_SERVER_HOST/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
      - git fetch
      - git checkout $CI_COMMIT_REF_NAME
      - git reset --hard origin/$CI_COMMIT_REF_NAME
      - git pull --rebase
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - source $HOME/.local/bin/env
      - uv tool install ruff@latest
  script:
    - ruff format src/
  after_script:
    - git add .
    - git commit -m "ruff update"
    - git push
  only:
    - merge_requests

build_package:
  stage: build
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
  script:
    - echo "Building with uv"
    - uv build
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.whl
  only:
    - main
 