image: "python:3.12"

stages:
  - linting
  - build

.lint_generic:
  stage: linting
  before_script:
      - git config --global user.name "Janitor"
      - git config --global user.email "squad@fz-juelich.de"
      - git remote set-url origin https://squad_janitor:$CI_FORMAT@$CI_SERVER_HOST/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
      - git fetch
      - git checkout $CI_COMMIT_REF_NAME
      - git reset --hard origin/$CI_COMMIT_REF_NAME
      - git pull --rebase
      - python3 -m pip install --upgrade pip autoflake black[jupyter]

black:
  extends: .lint_generic
  script:
    - black src/
  after_script:
    - git add .
    - git commit -m "black update"
    - git push
  only:
    - merge_requests

flake8:
  extends: .lint_generic
  script:
    - autoflake --remove-all-unused-imports --in-place --ignore-init-module-imports --recursive src/
  after_script:
    - git add .
    - git commit -m "flake8 update"
    - git push
  only:
    - merge_requests

build-test:
  stage: build
  script:
    - pip install -e .
  only:
    - merge_requests